<a href="https://colab.research.google.com/github/davillegasm/AP0053-20243/blob/tuplas-loops/udmy18.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
import pandas as pd

insta = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/analisisDatos/Archivos necesarios/Instagram.csv')
insta["reg date"] = pd.to_datetime(insta["reg date"])
insta["last login"] = pd.to_datetime(insta["last login"])
insta["gender"] = insta["gender"].astype("category")
insta["Country"] = insta["Country"].astype("category")
insta["Influencer"] = insta["Influencer"].astype("bool")
insta.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1016 entries, 0 to 1015
Data columns (total 9 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   first name  1016 non-null   object
 1   last name   1016 non-null   object
 2   gender      979 non-null    category
 3   reg date    1016 non-null   datetime64[ns]
 4   last login  1016 non-null   datetime64[ns]
 5   followers   1016 non-null   int64
 6   posts       1016 non-null   int64
 7   Influencer  1016 non-null   bool
 8   Country     1004 non-null   category
dtypes: bool(1), category(2), datetime64[ns](2), int64(2), object(2)
memory usage: 51.2+ KB

In [ ]:
insta.head(3)

,first name,last name,gender,reg date,last login,followers,posts,Influencer,Country
0,Corilla,Leuchars,Female,2011-02-11,2020-05-14 03:51:00,24536,462,False,Brazil
1,Forster,Gush,Male,2015-04-02,2020-07-11 07:41:00,8479,2581,True,United States
2,Everard,Jowers,Male,2018-11-14,2020-05-31 17:36:00,9356,6874,False,United Kingdom

In [ ]:
insta[insta["gender"] == "Male"]
insta[insta["Country"] == "Australia"]

,first name,last name,gender,reg date,last login,followers,posts,Influencer,Country
3,Bob,Threader,Male,2019-06-13,2020-07-04 16:19:00,33319,3617,False,Australia
15,Rolph,Ellcome,Male,2017-01-16,2020-11-11 13:25:00,26221,7048,True,Australia
19,Jamie,Moxted,Male,2015-12-31,2020-09-10 01:43:00,11115,6839,True,Australia
20,Clemens,Duncanson,Male,2015-07-14,2020-10-23 13:00:00,24440,7424,True,Australia
27,Correna,Gresser,Female,2011-10-20,2020-11-27 22:17:00,20773,3982,False,Australia
...,...,...,...,...,...,...,...,...,...
995,Sherwood,Wareing,Male,2018-09-27,2020-08-27 15:35:00,7493,540,True,Australia
998,Suki,Ansteys,Female,2018-06-02,2020-10-05 21:26:00,17733,788,True,Australia
1000,Devonne,Orritt,Female,2018-06-20,2020-05-10 14:25:00,37812,5400,False,Australia
1001,Gayelord,McKernon,Male,2012-02-20,2020-09-22 18:50:00,9057,5232,True,Australia
1002,Osmund,Gebuhr,Male,2020-07-28,2020-12-01 13:52:00,3012,317,False,Australia

In [ ]:
mask = insta["gender"] == "Female"
insta[mask]

,first name,last name,gender,reg date,last login,followers,posts,Influencer,Country
0,Corilla,Leuchars,Female,2011-02-11,2020-05-14 03:51:00,24536,462,False,Brazil
4,Deeann,Standell,Female,2011-04-26,2020-10-03 06:16:00,2908,98,False,NaN
5,Ashla,Ellingham,Female,2015-07-22,2020-12-12 03:10:00,15251,4397,True,Brazil
7,Linn,Easman,Female,2011-02-26,2020-10-19 07:22:00,34752,3899,False,Canada
8,Celia,Yurkov,Female,2013-02-02,2020-08-05 14:03:00,5977,1969,True,United States
...,...,...,...,...,...,...,...,...,...
1005,Shae,Blackaller,Female,2020-02-25,2020-12-18 20:27:00,2638,5965,False,Japan
1007,Bibby,Siward,Female,2020-10-19,2020-08-14 00:14:00,1668,1008,True,South Africa
1009,Yasmin,Deegan,Female,2010-03-19,2020-06-21 10:54:00,10118,4714,True,South Africa
1013,Pattie,Goody,Female,2015-11-09,2020-07-07 14:41:00,32425,6376,True,United States
1015,Regine,Bernholt,Female,2013-11-15,2020-05-23 14:23:00,19535,6927,True,Canada

In [ ]:
insta[insta["Influencer"] == True]

,first name,last name,gender,reg date,last login,followers,posts,Influencer,Country
1,Forster,Gush,Male,2015-04-02,2020-07-11 07:41:00,8479,2581,True,United States
5,Ashla,Ellingham,Female,2015-07-22,2020-12-12 03:10:00,15251,4397,True,Brazil
8,Celia,Yurkov,Female,2013-02-02,2020-08-05 14:03:00,5977,1969,True,United States
9,Torey,Leighfield,Female,2014-01-19,2020-12-14 14:33:00,6870,3994,True,Japan
11,Sheila,Jewkes,NaN,2020-02-24,2020-06-19 17:15:00,13224,5146,True,United Kingdom
...,...,...,...,...,...,...,...,...,...
1009,Yasmin,Deegan,Female,2010-03-19,2020-06-21 10:54:00,10118,4714,True,South Africa
1010,Thaxter,Fancett,Male,2014-04-10,2020-11-15 06:36:00,27146,876,True,Japan
1013,Pattie,Goody,Female,2015-11-09,2020-07-07 14:41:00,32425,6376,True,United States
1014,Sol,Andrysek,Male,2011-02-19,2020-10-18 16:06:00,475,7409,True,Brazil
1015,Regine,Bernholt,Female,2013-11-15,2020-05-23 14:23:00,19535,6927,True,Canada

In [ ]:
mask1 = insta["Country"] != "United States"
insta[mask1]

,first name,last name,gender,reg date,last login,followers,posts,Influencer,Country
0,Corilla,Leuchars,Female,2011-02-11,2020-05-14 03:51:00,24536,462,False,Brazil
2,Everard,Jowers,Male,2018-11-14,2020-05-31 17:36:00,9356,6874,False,United Kingdom
3,Bob,Threader,Male,2019-06-13,2020-07-04 16:19:00,33319,3617,False,Australia
4,Deeann,Standell,Female,2011-04-26,2020-10-03 06:16:00,2908,98,False,NaN
5,Ashla,Ellingham,Female,2015-07-22,2020-12-12 03:10:00,15251,4397,True,Brazil
...,...,...,...,...,...,...,...,...,...
1010,Thaxter,Fancett,Male,2014-04-10,2020-11-15 06:36:00,27146,876,True,Japan
1011,Lars,Crisp,Male,2012-12-30,2020-12-11 08:20:00,787,388,False,Canada
1012,Yvon,Goodbur,Male,2011-09-29,2020-09-20 17:36:00,18906,3851,False,Canada
1014,Sol,Andrysek,Male,2011-02-19,2020-10-18 16:06:00,475,7409,True,Brazil
1015,Regine,Bernholt,Female,2013-11-15,2020-05-23 14:23:00,19535,6927,True,Canada

In [ ]:
import pandas as pd
courses = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/analisisDatos/Archivos necesarios/COLLEGE - Courses.csv')
grades = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/analisisDatos/Archivos necesarios/COLLEGE - Grades.csv')
students = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/analisisDatos/Archivos necesarios/COLLEGE - Students.csv')

In [ ]:
courses

  course_id              course_name semester
0    BIO101  introduction to biology     fall
1    CSC098       data visualization   summer
2    CSC220            data analysis   spring
3    DBA305  database administration   spring
4    ECN322    cost benefit analysis   summer
5    ECN433            globalization     fall
6    MTH230                  vectors     fall

In [ ]:
grades.head()

   grade  student_id course_id
0     85        2323    CSC098
1     90        2323    DBA305
2     90        2329    CSC098
3     90        2329    DBA305
4     95        2329    ECN322

In [ ]:
students.head()

   student_id first_name last_name  gender
0        2323         tj     adams    male
1        2326  christine     adams     NaN
2        2329       paul   fischer    male
3        2332       abby    badmus  female
4        2335      maria     jones     NaN

In [ ]:
pd.merge(students, grades, on = 'student_id').head()

   student_id first_name last_name gender  grade course_id
0        2323         tj     adams   male     85    CSC098
1        2323         tj     adams   male     90    DBA305
2        2329       paul   fischer   male     90    CSC098
3        2329       paul   fischer   male     90    DBA305
4        2329       paul   fischer   male     95    ECN322

In [ ]:
df = pd.merge(students, grades, on = 'student_id').sort_values('grade', ascending = False).head(10)
df.head()

    student_id first_name last_name  gender  grade course_id
19        2359     joanne     price  female    100    ECN433
25        2368    melinda     smart  female     98    ECN322
23        2368    melinda     smart  female     98    CSC220
9         2338    johnson     banky    male     98    CSC098
21        2365         rj      lara    male     96    CSC098

In [ ]:
df['student_id'] == 2332
df[df['student_id'] == 2332]

   student_id first_name last_name  gender  grade course_id
7        2332       abby    badmus  female     94    MTH230
6        2332       abby    badmus  female     93    DBA305

In [ ]:
df[df['student_id'] == 2368]

    student_id first_name last_name  gender  grade course_id
25        2368    melinda     smart  female     98    ECN322
23        2368    melinda     smart  female     98    CSC220

In [ ]:
students_rec = students.merge(grades, on = 'student_id')
students_rec.head()

   student_id first_name last_name gender  grade course_id
0        2323         tj     adams   male     85    CSC098
1        2323         tj     adams   male     90    DBA305
2        2329       paul   fischer   male     90    CSC098
3        2329       paul   fischer   male     90    DBA305
4        2329       paul   fischer   male     95    ECN322

In [ ]:
students_rec1 = students_rec.merge(courses, on = 'course_id')
students_rec1.head()

,student_id,first_name,last_name,gender,grade,course_id,course_name,semester
0,2323,tj,adams,male,85,CSC098,data visualization,summer
1,2323,tj,adams,male,90,DBA305,database administration,spring
2,2329,paul,fischer,male,90,CSC098,data visualization,summer
3,2329,paul,fischer,male,90,DBA305,database administration,spring
4,2329,paul,fischer,male,95,ECN322,cost benefit analysis,summer

In [ ]:
reg_course = students_rec1.groupby('course_name')
reg_course.size().sort_values()

course_name
introduction to biology    2
data analysis              3
cost benefit analysis      4
globalization              6
data visualization         7
database administration    8
vectors                    8
dtype: int64

In [ ]:
students_records = students_rec1.groupby(['course_name', 'last_name', 'first_name', 'grade'])

In [ ]:
students_records.size()

course_name              last_name  first_name  grade
cost benefit analysis    andrew     melissa     90       1
                         banky      johnson     90       1
                         fischer    paul        95       1
                         smart      melinda     98       1
data analysis            banky      johnson     90       1
                         lara       rj          90       1
                         smart      melinda     98       1
data visualization       abubarka   fatima      85       1
                         adams      tj          85       1
                         banky      johnson     98       1
                         ceasar     romeo       80       1
                         fischer    paul        90       1
                         lara       rj          96       1
                         sylvester  tobias      90       1
database administration  abubarka   fatima      90       1
                         adams      tj          90       1
                         badmus     abby        93       1
                         fischer    paul        90       1
                         jones      maria       80       1
                         patterson  kevin       90       1
                         singh      pooja       87       1
                         smart      melinda     90       1
globalization            abubarka   fatima      95       1
                         anderson   abigael     80       1
                         brent      max         87       1
                         price      joanne      100      1
                         schmidts   paula       87       1
                         smart      melinda     90       1
introduction to biology  andrew     melissa     92       1
                         cooper     alice       95       1
vectors                  abubarka   fatima      90       1
                         anderson   abigael     82       1
                         badmus     abby        94       1
                         banky      johnson     85       1
                         drogba     george      87       1
                         fischer    paul        92       1
                         jones      christine   90       1
                         sylvester  tobias      80       1
dtype: int64

In [ ]:
students_rec1.head()

,student_id,first_name,last_name,gender,grade,course_id,course_name,semester
0,2323,tj,adams,male,85,CSC098,data visualization,summer
1,2323,tj,adams,male,90,DBA305,database administration,spring
2,2329,paul,fischer,male,90,CSC098,data visualization,summer
3,2329,paul,fischer,male,90,DBA305,database administration,spring
4,2329,paul,fischer,male,95,ECN322,cost benefit analysis,summer

In [ ]:
grades.head()

   grade  student_id course_id
0     85        2323    CSC098
1     90        2323    DBA305
2     90        2329    CSC098
3     90        2329    DBA305
4     95        2329    ECN322